{{/* Make sure all variables are set properly */}}
{{- include "common.values.setup" . }}

{{/* Append the configMap to the additionalVolumes */}}
{{- define "mariadb.configmap.volume" -}}
name: mariadb-settings
configMap:
  name: {{ template "common.names.fullname" . }}-config
{{- end -}}

{{- $volume := include "mariadb.configmap.volume" . | fromYaml -}}
{{- if $volume -}}
    {{- $additionalVolumes := append .Values.additionalVolumes $volume }}
    {{- $_ := set .Values "additionalVolumes" (deepCopy $additionalVolumes) -}}
{{- end -}}

{{/* Append the configMap volume to the additionalVolumeMounts */}}
{{- define "mariadb.configmap.volumeMount" -}}
name: mariadb-settings
mountPath: /etc/mysql/conf.d/custom.cnf
subPath: custom.cnf
{{- end -}}

{{- $volumeMount := include "mariadb.configmap.volumeMount" . | fromYaml -}}
{{- if $volumeMount -}}
    {{- $additionalVolumeMounts := append .Values.additionalVolumeMounts $volumeMount }}
    {{- $_ := set .Values "additionalVolumeMounts" (deepCopy $additionalVolumeMounts) -}}
{{- end -}}

{{/* Render the templates */}}
{{ include "common.all" . }}
